version: 2
jobs:
  build:
    working_directory: ~/my-project
    docker:
      - image: circleci/node:8-browsers
    steps:
      - checkout
      - restore_cache:
          key: CircleCI-{{ .Branch }}-{{ checksum "package.json" }}
      - run: npm install
      - save_cache:
          key: CircleCI-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - "node_modules"
      - run: xvfb-run -a npm run test -- --watch=false --no-progress --browsers=ChromeNoSandbox
      # - run: xvfb-run -a npm run e2e -- --no-progress --config=protractor-ci.conf.js
     
 deploy:
    machine:
      enabled: true
    working_directory: ~/my-project
    steps:
       - run:
          name: Deploy
          command: 'aws s3 sync ${source}/ s3://${bucket} --region us-west-2'