version: 2
jobs:
  build:
    working_directory: ~/my-project
    docker:
      - image: circleci/node:8-browsers
    steps:
      - checkout
      - restore_cache:
          key: CircleCI-{{ .Branch }}-{{ checksum "package.json" }}
      - run: npm install
      - save_cache:
          key: CircleCI-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - "node_modules"
      - run: xvfb-run -a npm run test -- --watch=false --no-progress --browsers=ChromeNoSandbox
      # - run: xvfb-run -a npm run e2e -- --no-progress --config=protractor-ci.conf.js
          
  deployment:
  staging:
    branch: master
    codedeploy:
      appname-1234:
        application_root: /
        region: us-east-1
        revision_location:
          revision_type: S3
          s3_location:
            bucket: my-bucket
            key_pattern: appname-1234-{BRANCH}-{SHORT_COMMIT}
        deployment_group: my-deployment-group