# version: 2
# jobs:
#   build:
#     working_directory: ~/CircleCI
#     docker:
#      - image: circleci/node:6.14.1-browsers
#     steps:
#       - checkout
#       - restore_cache:
#           key: CircleCI-{{ .Branch }}-{{ checksum "package.json" }}
#       - run: npm install
#       - save_cache:
#           key: CircleCI-{{ .Branch }}-{{ checksum "package.json" }}
#           paths:
#             - "node_modules"
#       - run: xvfb-run -a npm run test -- --watch=false --no-progress --browsers=ChromeNoSandbox
      # - run: xvfb-run -a npm run e2e -- --no-progress --config=protractor-ci.conf.js

#   deploy:
   
#     docker:
#         - image: circleci/node:6.14.1-browsers
#          working_directory: ~/CircleCI
#       steps:
#       - attach_workspace:
#          at: ~/CircleCI
#       - run:
#           name: Deploy
#           command: 'aws s3 sync ${build_folder}/ s3://${bucket}'

#  workflows:
#   version: 2
#   build-and-deploy:
#     jobs:
#       - build
#       - deploy:
#           requires:
#             - build
#           filters:
#             branches:
#               only: master


version: 2
jobs:
  build:
    working_directory: ~/${project_name}
    docker:
      - image: circleci/node:8-browsers
    steps:
      - checkout
      # - run:
      #     name: install-yarn
      #     command: 'curl -o- -L https://yarnpkg.com/install.sh | bash'
      - restore_cache:
          key: CircleCI-{{ .Branch }}-{{ checksum "package.json" }}
      - run: npm install
      - save_cache:
          key: CircleCI-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - "node_modules"
      - run:
          name: build
          command: 'ng build'
      - run: xvfb-run -a npm run test -- --watch=false --no-progress --browsers=ChromeNoSandbox

  deploy:
    docker:
      - image: circleci/node:8-browsers
    working_directory: ~/${project_name}
    steps:
      - attach_workspace:
         at: ~/${project_name}
      - run:
          name: Deploy
          command: 'aws s3 sync ${build_folder}/ s3://${bucket}'

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master